version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ioredis
    versions:
    - 4.24.6
